# Generated by Django 6.0 on 2026-01-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
