# Generated by Django 6.0 on 2026-01-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_food_protein_alter_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='preference',
            field=models.CharField(choices=[('low', 'Low Calorie'), ('high_protein', 'High Protein'), ('economic', 'Economic')], default='low', max_length=20),
        ),
    ]
