# Generated by Django 6.0 on 2026-01-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_simpleuser_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleuser',
            name='preference',
        ),
        migrations.AddField(
            model_name='simpleuser',
            name='strategy_type',
            field=models.CharField(choices=[('low_calorie', 'کم\u200cکالری'), ('high_protein', 'پروتئینی'), ('economic', 'اقتصادی')], default='low_calorie', max_length=20),
        ),
    ]
